# Generated by Django 3.0.8 on 2020-07-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foreign_Cigarette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField(default=0)),
                ('Tar', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('Nicotine', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('StarPoints', models.PositiveIntegerField(default=0)),
                ('StarPoint', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Foreign_Cigarette_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foreign_Cigarette_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=100)),
                ('StarPoint', models.PositiveSmallIntegerField(default=0)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='Foreign_Cigarette_App.Foreign_Cigarette')),
            ],
        ),
    ]
