# Generated by Django 3.0.8 on 2020-07-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic_Cigarette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField(default=0)),
                ('Tar', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('Nicotine', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
