# Generated by Django 3.0.8 on 2020-07-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cigarette_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
