# Generated by Django 3.0.8 on 2020-07-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0002_cigarette_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cigarette_Category',
            new_name='Domestic_Cigarette_Category',
        ),
    ]
