# Generated by Django 3.0.8 on 2020-07-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0003_auto_20200715_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic_Cigarette_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=100)),
                ('StarPoint', models.SmallIntegerField(default=0)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domestic_Cigarette_App.Domestic_Cigarette')),
            ],
        ),
    ]
