# Generated by Django 3.0.8 on 2020-07-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0005_auto_20200715_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestic_cigarette_comment',
            name='Object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domestic_Cigarette_App.Domestic_Cigarette'),
        ),
    ]
