# Generated by Django 3.0.8 on 2020-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0007_auto_20200715_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domestic_cigarette_comment',
            name='StarPoint',
        ),
    ]
