# Generated by Django 3.0.8 on 2020-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0009_domestic_cigarette_comment_starpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestic_cigarette',
            name='StarPoint',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domestic_cigarette',
            name='StarPoints',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
