# Generated by Django 3.0.8 on 2020-07-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domestic_Cigarette_App', '0010_auto_20200715_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestic_cigarette',
            name='StarPoint',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='domestic_cigarette',
            name='StarPoints',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
