# Generated by Django 3.0.8 on 2020-07-22 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Domestic_Cigarette_App', '0014_auto_20200722_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestic_cigarette_comment',
            name='Nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='D_Nickname', to=settings.AUTH_USER_MODEL),
        ),
    ]
